//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteFormsTemp.TempService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TempService.TempSoap")]
    public interface TempSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaTemperatura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultaTemperatura(string formato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaTemperatura", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultaTemperaturaAsync(string formato);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TempSoapChannel : ClienteFormsTemp.TempService.TempSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempSoapClient : System.ServiceModel.ClientBase<ClienteFormsTemp.TempService.TempSoap>, ClienteFormsTemp.TempService.TempSoap {
        
        public TempSoapClient() {
        }
        
        public TempSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TempSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ConsultaTemperatura(string formato) {
            return base.Channel.ConsultaTemperatura(formato);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultaTemperaturaAsync(string formato) {
            return base.Channel.ConsultaTemperaturaAsync(formato);
        }
    }
}
